name: Setup tldraw/tldraw
description: Set up node & npm

runs:
  using: composite
  steps:
    - name: Setup Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: 22.16.0
        cache: "npm"

    - name: Install dependencies
      run: npm ci
      shell: bash
